\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
setwd("/home/guest/Chen-Thompson-Project")

# Load your packages
library(dplyr)
library(ggplot2)
library(tidyverse)

# Set your ggplot theme
mytheme <- theme_classic(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)

# Load your datasets
CO2_cleaned_rest <- read.csv("~/Chen-Thompson-Project/Data/Raw/CO2_cleaned_restructured.csv", stringsAsFactors = TRUE)
CO2_cleaned <- read.csv("~/Chen-Thompson-Project/Data/Raw/CO2_cleaned.csv", stringsAsFactors = TRUE)
QoL_Classes <- read.csv("~/Chen-Thompson-Project/Data/Raw/QoL_Classes.csv", stringsAsFactors = TRUE)
QoL_Cleaned <- read.csv("~/Chen-Thompson-Project/Data/Raw/QoL_cleaned.csv", stringsAsFactors = TRUE)

```


# Rationale and Research Questions
    #### Contains clear context for research topic
      Contains rationale for dataset of choice
      Contains one or more questions of an appropriate scope
      for the projec


\newpage

# Dataset Information
    ####Describes source and content of data
    Details the wrangling process from raw to processed data
    Contains a table summarizing the dataset structure


\newpage

# Exploratory Analysis 
    ####Flow between text and visualizations is cohesive
    Relevant exploratory information is visualized


\newpage

# Analysis
    ####Flow between text and visualizations is cohesive
    Visualizations and statistical tests pertain directly to
    specific questions
    Statistical results are reported in plain language with
    relevant statistical output in parentheses
    Findings are reported clearly in relation to research
    questions


## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions
   ####Major findings are summarized
   Conclusions relate back to the original research context

\newpage

# References
<add references here if relevant, otherwise delete this section> 
